_target_: tabmonet.models.base.RealTabMONet
n_blocks: 3
expansion_factor: 1
n_features: ${dataset.n_features}
feature_dim: ${feature_dim}
emb_dim: 256
n_class: ${dataset.n_class}
problem_type: ${dataset.problem_type}
numerical_encoder: ${numerical_encoder}
categorical_encoder: null